######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 17 17:00:06 2013
######################################################################

TEMPLATE = app
TARGET = simulator
DEPENDPATH += .
INCLUDEPATH +=  common/inc models/inc loadBalancing/inc events/inc cache/inc readTraces/inc readAhead/inc 
CONFIG += debug
OBJECTS_DIR = .obj
MOC_DIR = .moc

# Input
SOURCES += common/src/main.cpp \
    common/src/DataType.cpp \
    models/src/RaidModel.cpp \
    common/src/GlobalState.cpp \
    models/src/LoadBalancerModel.cpp \
    common/src/Modeler.cpp \
    common/src/SettingsReader.cpp \
    models/src/StorageModel.cpp \
    models/src/StorageProcessorModel.cpp \
    models/src/ApplicationModel.cpp \
    cache/src/Cache.cpp \
    loadBalancing/src/RoundRobin.cpp \
    cache/src/CacheLine.cpp \
    common/src/ReadRequest.cpp \
    common/src/TimeUtil.cpp \
    readTraces/src/SequentialReadTrace.cpp \
    readTraces/src/ReadTraceFactory.cpp \
    readTraces/src/RandomReadTrace.cpp \
    readTraces/src/UserDefinedReadTrace.cpp \
    readTraces/src/TraceFileReader.cpp \
    readTraces/src/TraceFileEntry.cpp \
    common/src/ResultsFileWriter.cpp \
    common/src/CommandLineArguments.cpp \
    common/src/AAMessageHandler.cpp \
    loadBalancing/src/LoadBalancingAlgorithmFactory.cpp \
    loadBalancing/src/MinQueueDepthAlgorithm.cpp \
    models/src/StorageProcessorsStatistic.cpp \
    events/src/Event.cpp \
    events/src/EventsParser.cpp \
    events/src/EventExecutor.cpp \
    common/src/LimitedThroughput.cpp \
    readAhead/src/ReadAheadDecisionMaker.cpp \
    readAhead/src/AbstractReadAheadDecisionMaker.cpp \
    readAhead/src/ReadAheadDecisionMakerFactory.cpp \
    readAhead/src/SmartReadAheadDecisionMaker.cpp \
    readTraces/src/IRandomReadTraceAddressGenerator.cpp \
    readTraces/src/RandomReadTraceGeneratorSelector.cpp \
    readTraces/src/NoneLocalityGenerator.cpp \
    readTraces/src/SpacialLocalityGenerator.cpp \
    readTraces/src/TimeLocalityGenerator.cpp \
    models/src/RedirectDecisionMaker.cpp \
    readAhead/src/StubReadAheadDecisionMaker.cpp

HEADERS += \
    common/inc/defines.h \
    models/inc/IStorageElement.h \
    common/inc/DataType.h \
    models/inc/ApplicationModel.h \
    models/inc/RaidModel.h \
    common/inc/GlobalState.h \
    models/inc/LoadBalancerModel.h \
    common/inc/Modeler.h \
    common/inc/SettingsReader.h \
    models/inc/StorageModel.h \
    models/inc/StorageProcessorModel.h \
    cache/inc/Cache.h \
    loadBalancing/inc/RoundRobin.h \
    cache/inc/CacheLine.h \
    common/inc/ReadRequest.h \
    common/inc/TimeUtil.h \
    readTraces/inc/IReadTrace.h \
    readTraces/inc/SequentialReadTrace.h \
    readTraces/inc/ReadTraceFactory.h \
    readTraces/inc/RandomReadTrace.h \
    readTraces/inc/UserDefinedReadTrace.h \
    readTraces/inc/TraceFileReader.h \
    readTraces/inc/TraceFileEntry.h \
    common/inc/ResultsFileWriter.h \
    common/inc/CommandLineArguments.h \
    common/inc/AAMessageHandler.h \
    loadBalancing/inc/ILoadBalancingAlgorithm.h \
    loadBalancing/inc/LoadBalancingAlgorithmFactory.h \
    loadBalancing/inc/MinQueueDepthAlgorithm.h \
    models/inc/StorageProcessorsStatistic.h \
    events/inc/Event.h \
    events/inc/EventsParser.h \
    events/inc/EventExecutor.h \
    common/inc/LimitedThroughput.h \
    readAhead/inc/ReadAheadDecisionMaker.h \
    readAhead/inc/AbstractReadAheadDecisionMaker.h \
    readAhead/inc/ReadAheadDecisionMakerFactory.h \
    readAhead/inc/SmartReadAheadDecisionMaker.h \
    readTraces/inc/IRandomReadTraceAddressGenerator.h \
    readTraces/inc/RandomReadTraceGeneratorSelector.h \
    readTraces/inc/NoneLocalityGenerator.h \
    readTraces/inc/SpacialLocalityGenerator.h \
    readTraces/inc/TimeLocalityGenerator.h \
    models/inc/RedirectDecisionMaker.h \
    readAhead/inc/StubReadAheadDecisionMaker.h

OTHER_FILES += \
    settings.ini
